name: Semgrep SAST Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-24.04

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Semgrep (acción oficial)
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
          output: semgrep-results.json
          json: true

      - name: Mostrar resultados
        run: cat semgrep-results.json

      - name: Guardar reporte
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.json
